version: '2'

services:
  grafana:
    image: grafana/grafana:latest
    network_mode: host
    user: '104'
    volumes: 
      - ./cli/configs/grafana/grafana.ini:/etc/grafana/grafana.ini:z
  prometheus:
    image: prom/prometheus
    network_mode: host

    volumes: 
      - ./cli/configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:z