{
  "id": 1,
  "uid": "EZwuOR47k",
  "orgId": 1,
  "name": "Prometheus",
  "type": "prometheus",
  "typeLogoUrl": "",
  "access": "proxy",
  "url": "http://localhost:9090",
  "password": "",
  "user": "",
  "database": "",
  "basicAuth": false,
  "basicAuthUser": "",
  "basicAuthPassword": "",
  "withCredentials": false,
  "isDefault": true,
  "jsonData": {
    "httpMethod": "POST"
  },
  "secureJsonFields": {},
  "version": 3,
  "readOnly": false
}
